### ISSUE TITLE
x509-viewcert doesn't seem to work

### ISSUE THREAD

**Issue by muirdm** [jobbflykt/x509-mode#5] opened 2020-08-28 21:39 UTC
If I open the following cert:

```
-----BEGIN CERTIFICATE-----
MIIFSjCCAzICCQDAuMSDsPUjMDANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJV
UzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDjAMBgNVBAoM
BUVtYWNzMRIwEAYDVQQLDAl4NTA5LW1vZGUxDzANBgNVBAMMBmJhbmFuYTAeFw0y
MDA4MjgyMTM2NDVaFw0yMTA4MjgyMTM2NDVaMGcxCzAJBgNVBAYTAlVTMQswCQYD
VQQIDAJDQTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEOMAwGA1UECgwFRW1hY3Mx
EjAQBgNVBAsMCXg1MDktbW9kZTEPMA0GA1UEAwwGYmFuYW5hMIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEAxHFTGWnyYxWcvmzNXeCDkuEgypM7OGLgeMFq
R4KGGZjVsu0Yqg7iznOw8aC+XmabJfwDkuatuwVoskjQLsUF8oH6UCGaQAwSU8oW
PGfclFqe/VVlaJZjkbrzIMUp6V5yV9RZZRGOs/3D57teNqQeRE2oMnXbgIWXiKHy
GbTy2p0BRIg0LPnnQRt2zJotCyM7c204Vh28RfI0sUTlQQ4+c++1HaeCxqAm9HT2
hI6eaJlnj1pVBp7sqdqHNR1ty+1dQJNadbYw0SNXHVDwWxTOlXSHPIshic1ssNoy
7BQCYyYGY+mH+cM3EbhsJwMSAQvbaTc37BH47GskQYynPkowVaprl8d8l1aJYfM0
DFlgv8p+SWJK0LVPa1q7YLus3bqEksGfFLYchJnJLNiVjsDTodAlMnOO9Jrbk0vb
VuX07vlNZvr6crc4Qlg+Ju2O7w3LewSZk8PuPjU+fPmVh+Qh6+wZJzZDNPogc24W
/w8B8ZRGKwsHAY4jCLbnBE6IlE9HmmOB7NHH8rijRxF/qefQ4hA641NQg3ORuvoL
tQhWX+r8eF8N+Y0ZekyW4Gnrq7x131iKQL1tiF6dEObKv8/cHzKpLKoGxkp3PGUS
KWBKWwoShfU5dYwTaEhQPXx4xsWV4ZFgZLdOcSe+eAmiL3Oe3pWJJV1a8zdnzMEt
vzG5vUMCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEASek4vJA7pwL3GgUA8Z3umuV/
EStqaohcWoyp7yp4xssdbtKuT9VYz8Ib3b2bOaTAyA4kicsYdZaXN8HoHdKcKAxE
DtaP4mCyv0opn0MTl1W6m+m7Cfb1vJfNTLfw7ygUQ6RvgkVuX/wZVqROd4+Id9KH
PtU4rW5R05xMBvC9Q7ifoQj2jXTZfoHth1A0ol9J35XzQTGcyUTUZVORwm44xamX
sN78iX1Me6ytwkecBLZgfT+cvmIEK9SatHwrfrrPDp4FisCGUaI6ow00C2N22xMI
beJMt+WtVZIrZkCFnF/JXKqb4Vn6Q4O5fP+Kgsjk9sU4KHYWJ9M5KmmYj4nOL+jj
S7DEws2u1DS9sbQVDGzq673HTsQPISq754n/P2+Ag+Mszdob7Le3TEp3t5YgxzX/
AFkCA/J6Pz4nLnY2Vf1qyw+2w4XREoGinVw6TTBcMVeRdbPlWlrV5Cjzwqz2sDg4
UfQWKdFJidoIWLQADRgieWFihEoAn4/tcdYPmVLUrCnFgKhvtgiiiup8a1HhewjO
PUHCBcBlKz28w1cddTq3DlsiJ7z66FcD/AFo+CJGopX4pL3iAj5h8lEUlTdH+joK
jC8ErzJ1uotShm7vNp6Glok3wKsxLEZKtwQXKza1Cf7ivGQmTlKYgqWEKFmgE/DG
RksViUZ+l4MVNT3EU1E=
-----END CERTIFICATE-----
```

And run `x509-viewcert`, I get this output:

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 13887065520885539632 (0xc0b8c483b0f52330)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: 
```

which doesn't seem complete. When I dump it on the command line with `openssl x509 -in cert.pem -text -noout` I get:

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 13887065520885539632 (0xc0b8c483b0f52330)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=CA, L=San Francisco, O=Emacs, OU=x509-mode, CN=banana
        Validity
            Not Before: Aug 28 21:36:45 2020 GMT
            Not After : Aug 28 21:36:45 2021 GMT
        Subject: C=US, ST=CA, L=San Francisco, O=Emacs, OU=x509-mode, CN=banana
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:c4:71:53:19:69:f2:63:15:9c:be:6c:cd:5d:e0:
                    83:92:e1:20:ca:93:3b:38:62:e0:78:c1:6a:47:82:
                    86:19:98:d5:b2:ed:18:aa:0e:e2:ce:73:b0:f1:a0:
                    be:5e:66:9b:25:fc:03:92:e6:ad:bb:05:68:b2:48:
                    d0:2e:c5:05:f2:81:fa:50:21:9a:40:0c:12:53:ca:
                    16:3c:67:dc:94:5a:9e:fd:55:65:68:96:63:91:ba:
                    f3:20:c5:29:e9:5e:72:57:d4:59:65:11:8e:b3:fd:
                    c3:e7:bb:5e:36:a4:1e:44:4d:a8:32:75:db:80:85:
                    97:88:a1:f2:19:b4:f2:da:9d:01:44:88:34:2c:f9:
                    e7:41:1b:76:cc:9a:2d:0b:23:3b:73:6d:38:56:1d:
                    bc:45:f2:34:b1:44:e5:41:0e:3e:73:ef:b5:1d:a7:
                    82:c6:a0:26:f4:74:f6:84:8e:9e:68:99:67:8f:5a:
                    55:06:9e:ec:a9:da:87:35:1d:6d:cb:ed:5d:40:93:
                    5a:75:b6:30:d1:23:57:1d:50:f0:5b:14:ce:95:74:
                    87:3c:8b:21:89:cd:6c:b0:da:32:ec:14:02:63:26:
                    06:63:e9:87:f9:c3:37:11:b8:6c:27:03:12:01:0b:
                    db:69:37:37:ec:11:f8:ec:6b:24:41:8c:a7:3e:4a:
                    30:55:aa:6b:97:c7:7c:97:56:89:61:f3:34:0c:59:
                    60:bf:ca:7e:49:62:4a:d0:b5:4f:6b:5a:bb:60:bb:
                    ac:dd:ba:84:92:c1:9f:14:b6:1c:84:99:c9:2c:d8:
                    95:8e:c0:d3:a1:d0:25:32:73:8e:f4:9a:db:93:4b:
                    db:56:e5:f4:ee:f9:4d:66:fa:fa:72:b7:38:42:58:
                    3e:26:ed:8e:ef:0d:cb:7b:04:99:93:c3:ee:3e:35:
                    3e:7c:f9:95:87:e4:21:eb:ec:19:27:36:43:34:fa:
                    20:73:6e:16:ff:0f:01:f1:94:46:2b:0b:07:01:8e:
                    23:08:b6:e7:04:4e:88:94:4f:47:9a:63:81:ec:d1:
                    c7:f2:b8:a3:47:11:7f:a9:e7:d0:e2:10:3a:e3:53:
                    50:83:73:91:ba:fa:0b:b5:08:56:5f:ea:fc:78:5f:
                    0d:f9:8d:19:7a:4c:96:e0:69:eb:ab:bc:75:df:58:
                    8a:40:bd:6d:88:5e:9d:10:e6:ca:bf:cf:dc:1f:32:
                    a9:2c:aa:06:c6:4a:77:3c:65:12:29:60:4a:5b:0a:
                    12:85:f5:39:75:8c:13:68:48:50:3d:7c:78:c6:c5:
                    95:e1:91:60:64:b7:4e:71:27:be:78:09:a2:2f:73:
                    9e:de:95:89:25:5d:5a:f3:37:67:cc:c1:2d:bf:31:
                    b9:bd:43
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         49:e9:38:bc:90:3b:a7:02:f7:1a:05:00:f1:9d:ee:9a:e5:7f:
         11:2b:6a:6a:88:5c:5a:8c:a9:ef:2a:78:c6:cb:1d:6e:d2:ae:
         4f:d5:58:cf:c2:1b:dd:bd:9b:39:a4:c0:c8:0e:24:89:cb:18:
         75:96:97:37:c1:e8:1d:d2:9c:28:0c:44:0e:d6:8f:e2:60:b2:
         bf:4a:29:9f:43:13:97:55:ba:9b:e9:bb:09:f6:f5:bc:97:cd:
         4c:b7:f0:ef:28:14:43:a4:6f:82:45:6e:5f:fc:19:56:a4:4e:
         77:8f:88:77:d2:87:3e:d5:38:ad:6e:51:d3:9c:4c:06:f0:bd:
         43:b8:9f:a1:08:f6:8d:74:d9:7e:81:ed:87:50:34:a2:5f:49:
         df:95:f3:41:31:9c:c9:44:d4:65:53:91:c2:6e:38:c5:a9:97:
         b0:de:fc:89:7d:4c:7b:ac:ad:c2:47:9c:04:b6:60:7d:3f:9c:
         be:62:04:2b:d4:9a:b4:7c:2b:7e:ba:cf:0e:9e:05:8a:c0:86:
         51:a2:3a:a3:0d:34:0b:63:76:db:13:08:6d:e2:4c:b7:e5:ad:
         55:92:2b:66:40:85:9c:5f:c9:5c:aa:9b:e1:59:fa:43:83:b9:
         7c:ff:8a:82:c8:e4:f6:c5:38:28:76:16:27:d3:39:2a:69:98:
         8f:89:ce:2f:e8:e3:4b:b0:c4:c2:cd:ae:d4:34:bd:b1:b4:15:
         0c:6c:ea:eb:bd:c7:4e:c4:0f:21:2a:bb:e7:89:ff:3f:6f:80:
         83:e3:2c:cd:da:1b:ec:b7:b7:4c:4a:77:b7:96:20:c7:35:ff:
         00:59:02:03:f2:7a:3f:3e:27:2e:76:36:55:fd:6a:cb:0f:b6:
         c3:85:d1:12:81:a2:9d:5c:3a:4d:30:5c:31:57:91:75:b3:e5:
         5a:5a:d5:e4:28:f3:c2:ac:f6:b0:38:38:51:f4:16:29:d1:49:
         89:da:08:58:b4:00:0d:18:22:79:61:62:84:4a:00:9f:8f:ed:
         71:d6:0f:99:52:d4:ac:29:c5:80:a8:6f:b6:08:a2:8a:ea:7c:
         6b:51:e1:7b:08:ce:3d:41:c2:05:c0:65:2b:3d:bc:c3:57:1d:
         75:3a:b7:0e:5b:22:27:bc:fa:e8:57:03:fc:01:68:f8:22:46:
         a2:95:f8:a4:bd:e2:02:3e:61:f2:51:14:95:37:47:fa:3a:0a:
         8c:2f:04:af:32:75:ba:8b:52:86:6e:ef:36:9e:86:96:89:37:
         c0:ab:31:2c:46:4a:b7:04:17:2b:36:b5:09:fe:e2:bc:64:26:
         4e:52:98:82:a5:84:28:59:a0:13:f0:c6:46:4b:15:89:46:7e:
         97:83:15:35:3d:c4:53:51
```

**Comment by bo0ts** [comment] 2021-04-26 08:35
👍  Same issue here. openssl version is LibreSSL 2.8.3

**Comment by mnewt** [comment] 2021-08-19 16:09
See PR #2 for a fix

**Comment by jobbflykt** [comment] 2022-06-04 12:07
Cannot reproduce. PR #2 has been merged but that seems unrelated.

**Closed by jobbflykt** 2022-06-04 12:07 UTC
